services:
  cloud-ru-hack-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME-postgres}
      POSTGRES_USER: ${DB_USER-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD-postgres}
    ports:
      - "${DB_PORT-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: